---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-app
  namespace: default
  labels:
    app:  api-app
spec:
  selector:
    matchLabels:
      app: api-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  api-app
    spec:
      containers:
      - name:  api-app
        image:  211125293311.dkr.ecr.us-east-1.amazonaws.com/api:master
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  5000
          name:  api-app
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-app
  namespace: default
spec:
  selector:
    app: api-app
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: api-app
    protocol: TCP
    port: 5000
    targetPort: 5000
   