---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ui-app
  namespace: default
  labels:
    app:  ui-app
spec:
  selector:
    matchLabels:
      app: ui-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ui-app
    spec:
      containers:
      - name:  ui-app
        image:  211125293311.dkr.ecr.us-east-1.amazonaws.com/ui:master
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  3000
          name:  ui-app
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ui-app
  namespace: default
spec:
  selector:
    app: ui-app
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: ui-app
    protocol: TCP
    port: 80
    targetPort: 3000
 